In [1]:
import numpy

In [2]:
numpy.array([1,2])

array([1, 2])

In [3]:
import numpy as np

In [4]:
np.array([3,4])

array([3, 4])

In [5]:
import pandas as pd

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
LinearRegression()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
from sklearn import linear_model

In [10]:
linear_model.LinearRegression()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
#from statsmodels import *

In [13]:
from sklearn.datasets import fetch_california_housing
cal_housing = fetch_california_housing()

In [14]:
cal = cal_housing.data

In [15]:
type(cal)

numpy.ndarray

In [16]:
cal

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [17]:
cal*cal

array([[6.93089550e+01, 1.68100000e+03, 4.87780297e+01, ...,
        6.53086420e+00, 1.43489440e+03, 1.49401729e+04],
       [6.89132420e+01, 4.41000000e+02, 3.89143543e+01, ...,
        4.45143254e+00, 1.43337960e+03, 1.49377284e+04],
       [5.26698548e+01, 2.70400000e+03, 6.86931916e+01, ...,
        7.85266047e+00, 1.43262250e+03, 1.49426176e+04],
       ...,
       [2.89000000e+00, 2.89000000e+02, 2.70976751e+01, ...,
        5.40857864e+00, 1.55472490e+03, 1.46942884e+04],
       [3.48643584e+00, 3.24000000e+02, 2.84037077e+01, ...,
        4.50801718e+00, 1.55472490e+03, 1.47185424e+04],
       [5.70540996e+00, 2.56000000e+02, 2.76120506e+01, ...,
        6.84859025e+00, 1.54999690e+03, 1.46991376e+04]])

In [18]:
cal.transpose()

array([[   8.3252    ,    8.3014    ,    7.2574    , ...,    1.7       ,
           1.8672    ,    2.3886    ],
       [  41.        ,   21.        ,   52.        , ...,   17.        ,
          18.        ,   16.        ],
       [   6.98412698,    6.23813708,    8.28813559, ...,    5.20554273,
           5.32951289,    5.25471698],
       ...,
       [   2.55555556,    2.10984183,    2.80225989, ...,    2.3256351 ,
           2.12320917,    2.61698113],
       [  37.88      ,   37.86      ,   37.85      , ...,   39.43      ,
          39.43      ,   39.37      ],
       [-122.23      , -122.22      , -122.24      , ..., -121.22      ,
        -121.32      , -121.24      ]])

In [19]:
np.transpose(cal)

array([[   8.3252    ,    8.3014    ,    7.2574    , ...,    1.7       ,
           1.8672    ,    2.3886    ],
       [  41.        ,   21.        ,   52.        , ...,   17.        ,
          18.        ,   16.        ],
       [   6.98412698,    6.23813708,    8.28813559, ...,    5.20554273,
           5.32951289,    5.25471698],
       ...,
       [   2.55555556,    2.10984183,    2.80225989, ...,    2.3256351 ,
           2.12320917,    2.61698113],
       [  37.88      ,   37.86      ,   37.85      , ...,   39.43      ,
          39.43      ,   39.37      ],
       [-122.23      , -122.22      , -122.24      , ..., -121.22      ,
        -121.32      , -121.24      ]])

In [20]:
cal[0,0]

8.3252

In [24]:
type(cal)

numpy.ndarray

In [28]:
df = pd.DataFrame(cal)

In [30]:
df.head(n=20)

0     1         2         3       4         5      6       7
0   8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1   8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2   7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3   5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4   3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
5   4.0368  52.0  4.761658  1.103627   413.0  2.139896  37.85 -122.25
6   3.6591  52.0  4.931907  0.951362  1094.0  2.128405  37.84 -122.25
7   3.1200  52.0  4.797527  1.061824  1157.0  1.788253  37.84 -122.25
8   2.0804  42.0  4.294118  1.117647  1206.0  2.026891  37.84 -122.26
9   3.6912  52.0  4.970588  0.990196  1551.0  2.172269  37.84 -122.25
10  3.2031  52.0  5.477612  1.079602   910.0  2.263682  37.85 -122.26
11  3.2705  52.0  4.772480  1.024523  1504.0  2.049046  37.85 -122.26
12  3.0750  52.0  5.322650  1.012821  1098.0  2.346154  37.85 -122.26
13  2.6736  52.0  4.000000  1.097701   345.0  1.982759  37.84 -122.26
14  1.9167  52.0  4.262903  1.009677  1212.0  1.954839  37.85 -122.26
15  2.1250  50.0  4.242424  1.071970   697.0  2.640152  37.85 -122.26
16  2.7750  52.0  5.939577  1.048338   793.0  2.395770  37.85 -122.27
17  2.1202  52.0  4.052805  0.966997   648.0  2.138614  37.85 -122.27
18  1.9911  50.0  5.343675  1.085919   990.0  2.362768  37.84 -122.26
19  2.6033  52.0  5.465455  1.083636   690.0  2.509091  37.84 -122.27

In [31]:
df.tail()

0     1         2         3       4         5      6       7
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

In [33]:
df.describe()

0             1             2             3             4  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

                  5             6             7  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [34]:
df1 = pd.read_csv("~/witan.asc/resources/LAS-contacts.csv")

/Users/michaelford/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
